services:
  - type: web
    name: onboarding-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

